# .github/workflows/cmake-release.yml
name: CMake Release Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.1'
        host: ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
        target: 'desktop'
        arch: ${{ matrix.os == 'windows-latest' && 'win64_mingw' || 'linux_gcc_64' }}
        path: ${{ matrix.os == 'windows-latest' && 'C:\\Qt' || '/opt/Qt' }}
        modules: 'qtcharts'
        tools: ${{ matrix.os == 'windows-latest' && 'tools_mingw1310' || '' }}
        install-deps: 'true'
        
    - name: Add MinGW to PATH (Windows only)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Adding MinGW to PATH"
        echo "C:\\Qt\\Tools\\mingw1310\\bin" >> $GITHUB_PATH
        
    - name: Configure CMake
      run: |
        cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_PREFIX_PATH=${{ matrix.os == 'windows-latest' && 'C:/Qt/6.8.1/mingw_64' || '/opt/Qt/6.8.1/gcc_64' }} \
          ${
            matrix.os == 'windows-latest' 
            && '-G MinGW Makefiles' 
            || ''
          } \
          ${{ matrix.os == 'windows-latest' && '-DCMAKE_C_COMPILER=C:/Qt/Tools/mingw1310/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Qt/Tools/mingw1310/bin/g++.exe' || '' }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Run Tests
      run: ctest --output-on-failure --build-config ${{ env.BUILD_TYPE }}
      working-directory: build

    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ZapretGUI-${{ matrix.os }}-${{ env.BUILD_TYPE }}
        path: build/
