name: Build Qt Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей на Windows
      - name: Установка MSYS2 и MinGW
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-tools
            mingw-w64-x86_64-qt6-declarative
          cache: true

      # Установка зависимостей на Linux
      - name: Установка зависимостей на Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-declarative-dev

      # Установка зависимостей на macOS
      - name: Установка зависимостей на macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install qt

      # Настройка окружения для Qt на macOS
      - name: Настройка PATH для Qt на macOS
        if: runner.os == 'macOS'
        run: echo "::add-path::$(brew --prefix qt)/bin"

      # Сборка проекта
      - name: Сборка проекта
        run: |
          mkdir build
          cd build
          qmake ../
          make -j$(nproc)

      # Выгрузка артефактов
      - name: Выгрузка артефактов
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: build/
