name: Build Qt Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Установка MSYS2 и MinGW
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-declarative
          cache: true

      - name: Настройка среды на Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
          
      - name: Установка зависимостей на Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt6-base-dev qt6-base-dev-tools qt6-declarative-dev

      - name: Настройка PATH для Qt на Linux (GHEnv)
        if: runner.os == 'Linux'
        run: echo "/usr/lib/qt6/bin" >> $GITHUB_PATH

      - name: Установка зависимостей на macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake qt

      - name: Настройка PATH для Qt на macOS
        if: runner.os == 'macOS'
        run: echo "$(brew --prefix qt)/bin" >> $GITHUB_PATH

      - name: Сборка проекта
        run: |
          mkdir build
          cd build
          ${{if: runner.os == 'Windows' && 'cmake -DCMAKE_PREFIX_PATH=C:\msys64\mingw64\qt6' || 'cmake ..'}}
          cmake --build . --config Release

      # Выгрузка артефактов
      - name: Выгрузка артефактов
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: build/
